# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PotholeDensityCalc
                                 A QGIS plugin
 Calculates densities of potholes and records intersections with a road network
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-30
        copyright            : (C) 2024 by Dean Findlay
        email                : d3an79@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PotholeDensityCalc class from file PotholeDensityCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pothole_density_calc import PotholeDensityCalc
    return PotholeDensityCalc(iface)
